apiVersion : apps/v1
kind: Deployment
metadata:
  name: examapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: examapp
  template:
    metadata:
      labels:
        app: hier stond een error
    spec:
      containers:
        - name: examapp 
          image: itvitaecontainerregistry.azurecr.io/examapp
          ports:
          - containerPort: 5000